ALTER TABLE sys_user
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户ID',
    MODIFY COLUMN username VARCHAR(50) NOT NULL COMMENT '用户名',
    MODIFY COLUMN password VARCHAR(255) NOT NULL COMMENT '登录密码',
    MODIFY COLUMN nickname VARCHAR(50) NOT NULL COMMENT '用户昵称',
    MODIFY COLUMN phone VARCHAR(20) NOT NULL COMMENT '手机号',
    MODIFY COLUMN email VARCHAR(100) NULL COMMENT '电子邮箱',
    MODIFY COLUMN avatar_url VARCHAR(255) NULL COMMENT '头像地址',
    MODIFY COLUMN staff_real_name VARCHAR(50) NULL COMMENT '茶艺师真实姓名',
    MODIFY COLUMN staff_id_card_no VARCHAR(30) NULL COMMENT '茶艺师身份证号',
    MODIFY COLUMN staff_certification_url VARCHAR(255) NULL COMMENT '茶艺师资质主图地址',
    MODIFY COLUMN staff_certification_images TEXT NULL COMMENT '茶艺师资质图片列表',
    MODIFY COLUMN staff_application_note VARCHAR(500) NULL COMMENT '茶艺师申请说明',
    MODIFY COLUMN staff_approval_status VARCHAR(20) NULL COMMENT '茶艺师审核状态',
    MODIFY COLUMN staff_approval_remark VARCHAR(255) NULL COMMENT '茶艺师审核备注',
    MODIFY COLUMN role VARCHAR(20) NOT NULL COMMENT '角色类型',
    MODIFY COLUMN enabled BIT NOT NULL DEFAULT b'1' COMMENT '是否启用',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE member_account
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '会员账户ID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户ID',
    MODIFY COLUMN balance DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT '账户余额',
    MODIFY COLUMN cumulative_recharge DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT '累计充值金额',
    MODIFY COLUMN cumulative_spend DECIMAL(10, 2) NOT NULL DEFAULT 0.00 COMMENT '累计消费金额',
    MODIFY COLUMN member_level VARCHAR(30) NOT NULL DEFAULT 'NORMAL' COMMENT '会员等级',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE tea_room_type
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '茶室类型ID',
    MODIFY COLUMN name VARCHAR(50) NOT NULL COMMENT '类型名称',
    MODIFY COLUMN description VARCHAR(255) NULL COMMENT '类型描述',
    MODIFY COLUMN base_price DECIMAL(10, 2) NOT NULL COMMENT '基础价格',
    MODIFY COLUMN pricing_mode VARCHAR(20) NOT NULL DEFAULT 'PER_ROOM' COMMENT '计费模式',
    MODIFY COLUMN min_capacity INT NOT NULL DEFAULT 1 COMMENT '最小容纳人数',
    MODIFY COLUMN max_capacity INT NOT NULL DEFAULT 99 COMMENT '最大容纳人数',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE tea_room
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '茶室ID',
    MODIFY COLUMN type_id BIGINT NOT NULL COMMENT '茶室类型ID',
    MODIFY COLUMN staff_user_id BIGINT NULL COMMENT '负责茶艺师用户ID',
    MODIFY COLUMN name VARCHAR(100) NOT NULL COMMENT '茶室名称',
    MODIFY COLUMN capacity INT NOT NULL COMMENT '茶室容量',
    MODIFY COLUMN enabled BIT NOT NULL DEFAULT b'1' COMMENT '是否启用',
    MODIFY COLUMN location VARCHAR(255) NULL COMMENT '茶室位置',
    MODIFY COLUMN image_url VARCHAR(255) NULL COMMENT '茶室图片地址',
    MODIFY COLUMN business_start_time TIME NOT NULL DEFAULT '09:00:00' COMMENT '营业开始时间',
    MODIFY COLUMN business_end_time TIME NOT NULL DEFAULT '22:00:00' COMMENT '营业结束时间',
    MODIFY COLUMN description TEXT NULL COMMENT '茶室描述',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE tea
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '茶品ID',
    MODIFY COLUMN name VARCHAR(100) NOT NULL COMMENT '茶品名称',
    MODIFY COLUMN category VARCHAR(50) NOT NULL COMMENT '茶品分类',
    MODIFY COLUMN price DECIMAL(10, 2) NOT NULL COMMENT '售价',
    MODIFY COLUMN stock INT NOT NULL COMMENT '库存数量',
    MODIFY COLUMN image_url VARCHAR(255) NULL COMMENT '茶品图片地址',
    MODIFY COLUMN description TEXT NULL COMMENT '茶品描述',
    MODIFY COLUMN enabled BIT NOT NULL DEFAULT b'1' COMMENT '是否上架',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE reservation
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '预约ID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '预约用户ID',
    MODIFY COLUMN tea_room_id BIGINT NOT NULL COMMENT '茶室ID',
    MODIFY COLUMN reserved_start_time DATETIME NOT NULL COMMENT '预约开始时间',
    MODIFY COLUMN reserved_end_time DATETIME NOT NULL COMMENT '预约结束时间',
    MODIFY COLUMN party_size INT NOT NULL DEFAULT 1 COMMENT '预约人数',
    MODIFY COLUMN status VARCHAR(32) NOT NULL COMMENT '预约状态',
    MODIFY COLUMN remark VARCHAR(255) NULL COMMENT '预约备注',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE review
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '评价ID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '评价用户ID',
    MODIFY COLUMN tea_room_id BIGINT NOT NULL COMMENT '茶室ID',
    MODIFY COLUMN reservation_id BIGINT NULL COMMENT '关联预约ID',
    MODIFY COLUMN rating INT NOT NULL COMMENT '评分',
    MODIFY COLUMN content TEXT NULL COMMENT '评价内容',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE equipment_report
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '设备报修ID',
    MODIFY COLUMN tea_room_id BIGINT NOT NULL COMMENT '茶室ID',
    MODIFY COLUMN reported_by BIGINT NOT NULL COMMENT '报修人用户ID',
    MODIFY COLUMN title VARCHAR(100) NOT NULL COMMENT '报修标题',
    MODIFY COLUMN content TEXT NOT NULL COMMENT '报修内容',
    MODIFY COLUMN status VARCHAR(20) NOT NULL COMMENT '报修状态',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE activity
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '活动ID',
    MODIFY COLUMN creator_user_id BIGINT NOT NULL DEFAULT 1 COMMENT '创建人用户ID',
    MODIFY COLUMN creator_role VARCHAR(20) NOT NULL DEFAULT 'ADMIN' COMMENT '创建人角色',
    MODIFY COLUMN title VARCHAR(100) NOT NULL COMMENT '活动标题',
    MODIFY COLUMN content TEXT NULL COMMENT '活动内容',
    MODIFY COLUMN start_time DATETIME NOT NULL COMMENT '开始时间',
    MODIFY COLUMN end_time DATETIME NOT NULL COMMENT '结束时间',
    MODIFY COLUMN capacity INT NOT NULL COMMENT '活动容量',
    MODIFY COLUMN image_url VARCHAR(255) NULL COMMENT '活动图片地址',
    MODIFY COLUMN status VARCHAR(20) NOT NULL COMMENT '活动状态',
    MODIFY COLUMN summary_content TEXT NULL COMMENT '活动总结内容',
    MODIFY COLUMN summary_submitted_at DATETIME NULL COMMENT '活动总结提交时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE activity_registration
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '活动报名ID',
    MODIFY COLUMN activity_id BIGINT NOT NULL COMMENT '活动ID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '报名用户ID',
    MODIFY COLUMN cancelled BIT NOT NULL DEFAULT b'0' COMMENT '是否已取消',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE product_order
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '订单ID',
    MODIFY COLUMN order_no VARCHAR(64) NOT NULL COMMENT '订单编号',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '下单用户ID',
    MODIFY COLUMN reservation_id BIGINT NULL COMMENT '关联预约ID',
    MODIFY COLUMN amount DECIMAL(10, 2) NOT NULL COMMENT '订单金额',
    MODIFY COLUMN status VARCHAR(20) NOT NULL COMMENT '订单状态',
    MODIFY COLUMN payment_method VARCHAR(20) NULL COMMENT '支付方式',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE order_item
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '订单明细ID',
    MODIFY COLUMN order_id BIGINT NOT NULL COMMENT '订单ID',
    MODIFY COLUMN tea_id BIGINT NOT NULL COMMENT '茶品ID',
    MODIFY COLUMN quantity INT NOT NULL COMMENT '数量',
    MODIFY COLUMN unit_price DECIMAL(10, 2) NOT NULL COMMENT '成交单价',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE favorite
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '收藏ID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户ID',
    MODIFY COLUMN target_id BIGINT NOT NULL COMMENT '收藏目标ID',
    MODIFY COLUMN target_type VARCHAR(30) NOT NULL COMMENT '收藏目标类型',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE consultation_session
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '咨询会话ID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '发起咨询的用户ID',
    MODIFY COLUMN order_id BIGINT NULL COMMENT '关联订单ID',
    MODIFY COLUMN tea_room_id BIGINT NULL COMMENT '关联茶室ID',
    MODIFY COLUMN admin_user_id BIGINT NULL COMMENT '接待管理员用户ID',
    MODIFY COLUMN status VARCHAR(20) NOT NULL COMMENT '会话状态',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE consultation_message
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '咨询消息ID',
    MODIFY COLUMN session_id BIGINT NOT NULL COMMENT '会话ID',
    MODIFY COLUMN sender_id BIGINT NOT NULL COMMENT '发送人用户ID',
    MODIFY COLUMN notify_admin BIT NOT NULL DEFAULT b'0' COMMENT '是否提醒管理员',
    MODIFY COLUMN notify_staff BIT NOT NULL DEFAULT b'0' COMMENT '是否提醒茶艺师',
    MODIFY COLUMN content TEXT NOT NULL COMMENT '消息内容',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE staff_complaint
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '员工投诉ID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '投诉用户ID',
    MODIFY COLUMN tea_room_id BIGINT NOT NULL COMMENT '茶室ID',
    MODIFY COLUMN staff_user_id BIGINT NOT NULL COMMENT '被投诉茶艺师用户ID',
    MODIFY COLUMN content TEXT NOT NULL COMMENT '投诉内容',
    MODIFY COLUMN status VARCHAR(20) NOT NULL COMMENT '投诉状态',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE member_recharge_record
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '充值记录ID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '充值用户ID',
    MODIFY COLUMN amount DECIMAL(10, 2) NOT NULL COMMENT '充值金额',
    MODIFY COLUMN balance_after DECIMAL(10, 2) NOT NULL COMMENT '充值后余额',
    MODIFY COLUMN operator_user_id BIGINT NULL COMMENT '操作人用户ID',
    MODIFY COLUMN remark VARCHAR(255) NULL COMMENT '备注',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE user_coupon
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户优惠券ID',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户ID',
    MODIFY COLUMN title VARCHAR(100) NOT NULL COMMENT '优惠券标题',
    MODIFY COLUMN coupon_code VARCHAR(64) NOT NULL COMMENT '优惠券编码',
    MODIFY COLUMN threshold_amount DECIMAL(10, 2) NOT NULL COMMENT '使用门槛金额',
    MODIFY COLUMN discount_amount DECIMAL(10, 2) NOT NULL COMMENT '优惠金额',
    MODIFY COLUMN source_level VARCHAR(30) NOT NULL COMMENT '发放来源等级',
    MODIFY COLUMN issued_week VARCHAR(20) NOT NULL COMMENT '发放批次周标识',
    MODIFY COLUMN status VARCHAR(20) NOT NULL COMMENT '优惠券状态',
    MODIFY COLUMN valid_from DATETIME NOT NULL COMMENT '生效时间',
    MODIFY COLUMN valid_until DATETIME NOT NULL COMMENT '失效时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE notification
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '通知ID',
    MODIFY COLUMN recipient_user_id BIGINT NOT NULL COMMENT '接收人用户ID',
    MODIFY COLUMN type VARCHAR(50) NOT NULL COMMENT '通知类型',
    MODIFY COLUMN title VARCHAR(120) NOT NULL COMMENT '通知标题',
    MODIFY COLUMN content TEXT NOT NULL COMMENT '通知内容',
    MODIFY COLUMN target_type VARCHAR(50) NULL COMMENT '关联目标类型',
    MODIFY COLUMN target_id BIGINT NULL COMMENT '关联目标ID',
    MODIFY COLUMN route_path VARCHAR(255) NULL COMMENT '跳转路径',
    MODIFY COLUMN is_read BIT NOT NULL DEFAULT b'0' COMMENT '是否已读',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE system_config
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '系统配置ID',
    MODIFY COLUMN config_key VARCHAR(100) NOT NULL COMMENT '配置键',
    MODIFY COLUMN config_value TEXT NOT NULL COMMENT '配置值',
    MODIFY COLUMN description VARCHAR(255) NULL COMMENT '配置说明',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
